Repository LeagueOfPoro/CapsuleFarmerEvolved, pull requests merged in 2023-02, with the labels that each got.

#54 fix: Fixed outdated source URL
  confighelper.html
Labels: bug

#52 feat: Handle rate limiting, refactor main.py
  Browser.py
  Exceptions/CapsuleFarmerEvolvedException.py
  Exceptions/RateLimitException.py
  Exceptions/StatusCodeAssertException.py
  StatusCodeAssertException.py
  main.py
Labels: enhancement

#48 feat: Discord Webhook Support
  FarmThread.py
Labels: enhancement

#78 fix: beststreams.txt not found
  src/Config.py
Labels: hotfix

#83 docs: Banner + readme changes
  .github/banner.png
  README.md
Labels: documentation

#56 fix: docker table display
  src/GuiThread.py
Labels: enhancement

#87 feat: Dynamically loading bestStreams from Url in config
  src/Config.py
Labels: enhancement

#97 fix: Properly close all connections
  src/Browser.py
Labels: bug, enhancement

#99 feat: Added time until next match, when there are no live matches.
  src/Browser.py
  src/FarmThread.py
Labels: enhancement

#115 feat: Move common tasks to a separate thread
  src/AssertCondition.py
  src/Browser.py
  src/DataProviderThread.py
  src/FarmThread.py
  src/SharedData.py
  src/main.py
Labels: enhancement, code quality

#96 feat: Added last drop league, to the last drop field
  src/FarmThread.py
  src/Stats.py
Labels: enhancement

#132 fix: Change LOGIN status color from green to yellow
  src/FarmThread.py
Labels: enhancement

#136 feat: Change status message
  src/FarmThread.py
Labels: enhancement

#150 feat: Show program version in log file
  src/Logger.py
  src/main.py
Labels: code quality

#104 feat: IMAP Integration for 2FA [BREAKING]
  Pipfile
  config/confighelper.html
  src/Browser.py
  src/Config.py
  src/DataProviderThread.py
  src/Exceptions/Fail2FAException.py
  src/Exceptions/FailFind2FAException.py
  src/Exceptions/InvalidIMAPCredentialsException.py
  src/FarmThread.py
  src/GuiThread.py
  src/IMAP.py
  src/Stats.py
  src/main.py
Labels: enhancement, DoNotMerge

#147 fix: Show correct time until next match
  src/DataProviderThread.py
  src/SharedData.py
Labels: enhancement

#156 fix: API "crashing"
  src/Browser.py
  src/DataProviderThread.py
  src/main.py
Labels: bug, enhancement

#162 feat: Print the time when the program started running
  src/main.py
Labels: enhancement

#131 feat: Adds the riot api key as a constant in the config class
  src/Config.py
  src/DataProviderThread.py
  src/FarmThread.py
Labels: enhancement, code quality

#158 feat: Fetch and show total drops per account from riot
  src/Browser.py
  src/Config.py
  src/FarmThread.py
  src/GuiThread.py
  src/Stats.py
Labels: enhancement, Update WIKI
